!
! Highly divisible triangular number
!
! Problem 12
!
! The sequence of triangle numbers is generated by adding the natural numbers.
! So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
! first ten terms would be:
!
!   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
!
! Let us list the factors of the first seven triangle numbers:
!
!      1: 1
!      3: 1,3
!      6: 1,2,3,6
!     10: 1,2,5,10
!     15: 1,3,5,15
!     21: 1,3,7,21
!     28: 1,2,4,7,14,28
!
! We can see that 28 is the first triangle number to have over five divisors.
! What is the value of the first triangle number to have over five hundred
! divisors?
!
program p_012
  use, intrinsic :: iso_fortran_env
  implicit none
  integer :: n, i, c, k, p
  n = 0
  i = 0
  do
     i = i + 1
     n = n + i
     c = 0
     p = int(sqrt(real(n)))
     do k = 1, p
        if (mod(n, k) == 0) c = c + 2
     end do
     if (p ** 2 == n) c = c - 1
     if (c > 500) exit
     !write(output_unit, '(*(i0," "))') n, c
  end do
  write(output_unit, '("solution: ",g0)') n
end program p_012
