!
! Even Fibonacci numbers
!
! Problem 2
!
! Each new term in the Fibonacci sequence is generated by adding the previous
! two terms. By starting with 1 and 2, the first 10 terms will be:
!
!     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
!
! By considering the terms in the Fibonacci sequence whose values do not exceed
! four million, find the sum of the even-valued terms.
!
program p_002
  use, intrinsic :: iso_fortran_env
  implicit none
  integer :: n1, n2, n3, sum
  n1 = 1
  n2 = 2
  sum = n2
  do
     n3 = n1 + n2
     if (n3 >= 4000000) exit
     if (mod(n3, 2) == 0) then
        sum = sum + n3
     end if
     n1 = n2
     n2 = n3
  end do
  write(output_unit, '("solution: ",g0)') sum
end program p_002
